# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = browserlib
DESTDIR = ../x64/Debug
CONFIG += staticlib debug
DEFINES += BROWSERLIB_LIB BUILD_STATIC
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(browserlib.pri)
